version: '3.8'

services:
  dotfiles-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotfiles-test
    volumes:
      # Mount the current directory for live testing
      - .:/opt/dotfiles:ro
      - dotfiles-cache:/root/.cache
      - ./config/sheldon:/root/.config/sheldon:ro
    environment:
      - DOTFILES_PROFILE=develop
      - DOTFILES_VERBOSE=true
    command: debug
    stdin_open: true
    tty: true

  dotfiles-minimal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotfiles-minimal
    volumes:
      - .:/opt/dotfiles:ro
      - minimal-cache:/root/.cache
      - ./config/sheldon:/root/.config/sheldon:ro
    environment:
      - DOTFILES_PROFILE=minimal
      - DOTFILES_VERBOSE=false
    command: test

  dotfiles-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotfiles-server
    volumes:
      - .:/opt/dotfiles:ro
      - server-cache:/root/.cache
      - ./config/sheldon:/root/.config/sheldon:ro
    environment:
      - DOTFILES_PROFILE=server
      - DOTFILES_VERBOSE=false
    command: test

volumes:
  dotfiles-cache:
  minimal-cache:
  server-cache:
